version: 2
jobs:
  build:
    working_directory: ~/pfm-app
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
      - checkout
      - restore_cache:
          key: pfm-app-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: pfm-app-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - store_artifacts:
          path: target/spring-boot-react-0.0.1-SNAPSHOT.jar